[package]
name = "mediatap"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.8.0" }
surf = "2.1.0"
xz2 = "0.1.6"
diesel = { version = "1.4", features = ["sqlite"] }
directories = "3.0.1"
json_minimal = "0.1.3"
diesel_migrations = "1.4.0"
clap = "3.0.0-beta.2"
